import React from 'react';
import logo from '../../../images/logo-white.svg';

class AboutPage extends React.Component {
  componentDidMount() {
    window.addEventListener('scroll', function(){
      if(0 !== document.body.scrollTop) document.getElementsByTagName("header")[0].classList.add("overlaid");
      else document.getElementsByTagName("header")[0].classList.remove("overlaid");
    });
  }

  render() {
    return (
      <div className="about">
        <header>
          <div id="header-wrapper">
            <a id="header-logo" href="#">
              <img id="primary-logo" src={logo}/>
            </a>

            <div className="header-menu-wrapper" onClick={this.toggleMenu}>|||</div>

            <div className="header-link-wrapper">
              <a className="header-link active" href="#/about">About</a>
              <div className="header-separator"></div>
              <a className="header-link" href="https://github.com/DevanaLabs/lemon.email-dApp" target="_blank">GitHub</a>
              <div className="header-separator"></div>
              <a className="header-link" href="#/auth">Login</a>
            </div>
          </div>
        </header>

        <div id="section-hero-wrapper">
          <div id="section-hero">
            <div className="fixed-width-section">
              <h1>About LemonMail DApp</h1>
              <h2>
                Motivation
              </h2>

              <p>Although there are already products that offer secure and private email services (such as <a href="https://protonmail.com" target="_blank">ProtonMail</a>),
                all of them still have to rely on some kind of central server which essentially becomes a single point of failure. After following emerging distributed technologies such as Ethereum and IPFS for some time,
                we have realised that it has become possible to create a messaging service that is both secure and completely decentralized. LemonMail DApp is a first attempt at creating such service. </p>

              <h2>
                Security
              </h2>

              <p>Like with other secure emails services, all message content is end-to-end encrypted before it leaves your browser and therefore can only be viewed by you and your correspondent.
                Encryption is achieved using public key cryptography, where a new private key is generated by signing a predefined message using your Ethereum account.
                This new private key never leaves your browser, but it's public counterpart gets broadcast on the Ethereum blockchain, so that others can encrypt messages before sending them to you.
                The DApp <b>does not</b> have direct access to your Ethereum private key. Encryption is done
                using <a href="https://github.com/bitpay/bitcore-lib" target="_blank">bitcore-lib</a> and <a href="https://github.com/bitpay/bitcore-ecies" target="_blank">bitcore-ecies</a> libraries.</p>

              <h2>
                External gateways
              </h2>

              <p>The DApp is completely decentralized when messages are exchanged between two DApp users.
                However, you can still send messages to regular email addresses (like GMail), since we are also running a SMTP service that is monitoring blockchain transactions
                and forwarding emails to the external users. In order for these external emails to remain secure, you will have to come up with a question
                to which only the receiver will know the answer. He will then have to provide this secret answer in order to decrypt email that was delivered to him. On the other hand,
              you can also receive emails from external users, but they should be sent to <i>yourusername@dapp.lemon.email</i> instead of your regular lemonmail.eth address.
              Keep in mind that security for these incoming external emails is not guaranteed, since they will usually go unencrypted through a number of different servers before reaching you.</p>

              <h2>
                Who is behind all this?
              </h2>

              <p>LemonMail DApp was developed by <a href="http://labs.devana.rs/" target="_blank">Devana Labs</a>, a small startup from Belgrade, Serbia. We like to push boundaries to see what our minds are capable of creating. We love to research and develop new ideas and explore cutting edge technologies.
                Devana Labs has been made with exactly that purpose – to stretch our thinking to an extreme and play with new and interesting ideas which can invent our future in a way.
                We are particularly interested in applications that inspire people's future use of technology. “Labs” as we internally call it builds pre-commercial prototypes of software and hardware products. Our current passion is blockchain and everything that has to do with decentralization.</p>
            </div>
          </div>
        </div>

        <footer>
          <h4><b>Lemon</b> DApp</h4>
          <a href="#/about">About</a>
          <a href="https://github.com/DevanaLabs/lemon.email-dApp" target="_blank">GitHub</a>
          <a href="https://lemon.email/contact" target="_blank">Contact us</a>
        </footer>
      </div>
    )
  }
}

export default AboutPage;